### ISSUE TITLE
关于 sublime的代码片段

### ISSUE THREAD

**Issue by Chankalam** [amazeui/snippets#1]
Sublime Text 2/3：打开 Preferences > Browse Packages. 在 Browse Packages 下创建 AmazeUI 目录，把 dist 目录 sublime 内的文件复制创建好的 AmazeUI 目录下。

请问哪里来的dist 目录?

**Comment by Minwe** [comment]
http://amazeui.org/download?ver=sublime 从这下载吧，那个描述有点问题

**Comment by Minwe** [comment]
@huangzhipeng 录制一个安装的 gif 图吧。

**Comment by Chankalam** [comment]
对于没有用过st的人来说实在看不懂

**Comment by Minwe** [comment]
@huangzhipeng 再检查一下这个

> 建议把.sublime-snippet代码片段中的第一个"<"删掉，每次输入都会多出一个左括号。

**Comment by huangzhipeng** [comment]
gif 已经录好，sublime 中没有找到 `<` 问题，Sublime Text 修复了行尾空格问题，WebStorm 修复换行问题。

**Comment by xc116** [comment]
你好，我安装了AmazeUI到Package，输入am-没有自动提示，只能在class属性中才能自动提示，我的问题可能出在哪里呢？ 还需要其他的插件吗

**Comment by heby** [comment]
OSX sublime3和webstorm9添加后均无法正常提示，必须在属性位置才有提示。

**Comment by wangwen1220** [comment]
怎么不发布到 packagecontrol.io 上？
