### ISSUE TITLE
jar文件导入的设置在jetbrains中html,php不生效

### ISSUE THREAD

**Issue by maxadjsky** [amazeui/snippets#10]
我的编辑器是phpStorm 2016.1.下载了jar文件导入设置后，发现Live Templates中的所有AmazeUI的设置都是只支持XML系列的文件，HTML系列和PHP等都需要手动添加。但是手动改起来实在太麻烦了！！！

**Comment by minwe** [comment]
现在还把 HTML 混在 PHP 文件中么？不做模板分离？

**Comment by minwe** [comment]
你重新下载导入导入一下，已经把 HTML、PHP、JSP 加上了。

**Comment by maxadjsky** [comment]
好的，已经重新下载了！Laravel框架默认的模板是php文件，而不是html文件。
