### ISSUE TITLE
webstorm windows安装路径有误

### ISSUE THREAD

**Issue by avatasia** [amazeui/snippets#3]
JetBrains 系列编辑器（WebStorm 等）：

    方式一：Mac 把下载解压得到的 AmazeUI.xml 拷贝到 ~/Library/Preferences/WebStorm9/templates 目录下，重启编辑器（WebStorm9 为相应编辑器的名称和版本）；Windows：%USERPROFILE%/.WebStorm9/config/ 目录下；

应为: %USERPROFILE%/.WebStorm9/config/templates
templates要手工建立.

**Comment by Minwe** [comment]
谢谢提醒。
