### ISSUE TITLE
am-cdn代码片段的错误，我提供一个正确的

### ISSUE THREAD

**Issue by goto911** [amazeui/snippets#7]
```
 <link rel="stylesheet" href="http://cdn.amazeui.org/amazeui/2.5.2/css/amazeui.min.css">
<script src="http://apps.bdimg.com/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://cdn.amazeui.org/amazeui/2.2.1/js/amazeui.min.js"></script>
```

为了版本一样，就用

**Comment by goto911** [comment]
<link rel="stylesheet" href="http://cdn.amazeui.org/amazeui/2.5.2/css/amazeui.min.css">
<script src="http://apps.bdimg.com/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://cdn.amazeui.org/amazeui/2.2.1/js/amazeui.min.js"></script>

**Comment by minwe** [comment]
这个项目有一段时间没有更新了，版本变化没有做调整。
