### ISSUE TITLE
希望增加vscode的代码片段

### ISSUE THREAD

**Issue by gofmt** [amazeui/snippets#9]
现在vscode相当好用了,请增加vscode的代码片段.

**Comment by minwe** [comment]
可以参考 https://code.visualstudio.com/docs/extensions/example-hello-world，结合本项目提供的内容，可以生成一个。

**Comment by minwe** [comment]
https://marketplace.visualstudio.com/items?itemName=minwe.amazeui-vscode-snippets 

```
ext install amazeui-vscode-snippets
```
